# Site settings
title: "Selfie-Upload Dokumentation"
description: "Offizielle Dokumentation des Selfie-Upload-Projekts"
baseurl: "/Selfie-Upload" # Passe dies an den Namen deines Repositories an
url: "https://flacoonb.github.io" # Deine GitHub Pages URL
repository: "flacoonb/Selfie-Upload" # Dein GitHub Repository

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Verwende das Minimal Mistakes Theme
plugins:
  - jekyll-remote-theme # Dies wird benötigt, um Remote-Themes zu verwenden

# Enable sidebar navigation
sidebar:
  nav: "docs"  # Dies aktiviert die Sidebar-Navigation

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true

# Navigation settings (Sidebar)
collections:
  docs:
    output: true

# Navigation links in the sidebar
navigation:
  docs:
    - title: "Startseite"
      url: "/Selfie-Upload/"
    - title: "Funktionen"
      url: "/Selfie-Upload/docs/features/"
    - title: "Installation"
      url: "/Selfie-Upload/docs/installation/"
    - title: "Anleitung & Nutzung"
      url: "/Selfie-Upload/docs/usage/"
    - title: "Sicherheitshinweise"
      url: "/Selfie-Upload/docs/securitynotes/"
    - title: "Lizenz"
      url: "/Selfie-Upload/docs/license/"
