# Site settings
title: "Selfie-Upload Dokumentation"
description: "Offizielle Dokumentation des Selfie-Upload-Projekts"
baseurl: "/Selfie-Upload" # Passe dies an den Namen deines Repositories an
url: "https://flacoonb.github.io" # Deine GitHub Pages URL
repository: "flacoonb/Selfie-Upload" # Dein GitHub Repository

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Verwende das Minimal Mistakes Theme
plugins:
  - jekyll-remote-theme # Dies wird benötigt, um Remote-Themes zu verwenden

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "single"
      author_profile: true
      read_time: true

# Enable sidebar navigation
sidebar:
  nav: docs  # Verweise auf den Namen der Navigation in _data/navigation.yml

# Navigation settings (Sidebar)
collections:
  docs:
    output: true
